apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpoenodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplenodeapp
  template:
    metadata:
      labels:
        app: simplenodeapp
    spec:
      containers:
      - name: simplenodeapp
        image: akubicharm/simplenodeapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: simplenodeapp
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: simplenodeapp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simplenodeapp
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: simplenodeapp.4451d2f1043c4c139d13.japaneast.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: simplenodeapp
            port:
              number: 80
